### ISSUE TITLE
ESP8266 Compile error

### ISSUE THREAD

**Issue by hipotenusa** [ArduinoGetStarted/led#1]
I am having some trouble compiling this library for ESP8266 Wemos D1 mini. I have installed the library though the Arduino Library Manager (v1.0.0). I have also tried downloading the zip from github and same thing. I am using Arduino version 1.8.19 under linux. Just with the include -no need to instantiate any object- I start getting quite a few compile errors.

> /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:34:1: error: default argument given for parameter 2 of 'ezLED::ezLED(int, int)' [-fpermissive]
   34 | ezLED::ezLED(int pin, int mode = CTRL_ANODE) {
      | ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:89:3: note: previous specification in 'ezLED::ezLED(int, int)' here
   89 |   ezLED(int pin, int mode = CTRL_ANODE);
      |   ^~~~~
/home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:81:6: error: default argument given for parameter 1 of 'void ezLED::turnON(long unsigned int)' [-fpermissive]
   81 | void ezLED::turnON(unsigned long delayTime = 0) {
      |      ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:90:8: note: previous specification in 'void ezLED::turnON(long unsigned int)' here
   90 |   void turnON(unsigned long delayTime = 0);
      |        ^~~~~~
/home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:95:6: error: default argument given for parameter 1 of 'void ezLED::turnOFF(long unsigned int)'
   95 | void ezLED::turnOFF(unsigned long delayTime = 0) {
      |      ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:91:8: note: previous specification in 'void ezLED::turnOFF(long unsigned int)' here
   91 |   void turnOFF(unsigned long delayTime = 0);
      |        ^~~~~~~
/home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:109:6: error: default argument given for parameter 1 of 'void ezLED::toggle(long unsigned int)'
  109 | void ezLED::toggle(unsigned long delayTime = 0) {
      |      ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:92:8: note: previous specification in 'void ezLED::toggle(long unsigned int)' here
   92 |   void toggle(unsigned long delayTime = 0);
      |        ^~~~~~
/home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:125:6: error: default argument given for parameter 4 of 'void ezLED::fade(int, int, long unsigned int, long unsigned int)' [-fpermissive]
  125 | void ezLED::fade(int fadeFrom, int fadeTo, unsigned long fadeTime, unsigned long delayTime = 0) {
      |      ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:94:8: note: previous specification in 'void ezLED::fade(int, int, long unsigned int, long unsigned int)' here
   94 |   void fade(int fadeFrom, int fadeTo, unsigned long fadeTime, unsigned long delayTime = 0);
      |        ^~~~
/home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:141:6: error: default argument given for parameter 3 of 'void ezLED::blink(long unsigned int, long unsigned int, long unsigned int)' [-fpermissive]
  141 | void ezLED::blink(unsigned long onTime, unsigned long offTime, unsigned long delayTime = 0) {
      |      ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:96:8: note: previous specification in 'void ezLED::blink(long unsigned int, long unsigned int, long unsigned int)' here
   96 |   void blink(unsigned long onTime, unsigned long offTime, unsigned long delayTime = 0);
      |        ^~~~~
/home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:159:6: error: default argument given for parameter 4 of 'void ezLED::blinkInPeriod(long unsigned int, long unsigned int, long unsigned int, long unsigned int)' [-fpermissive]
  159 | void ezLED::blinkInPeriod(unsigned long onTime, unsigned long offTime, unsigned long blinkTime, unsigned long delayTime = 0) {
      |      ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:97:8: note: previous specification in 'void ezLED::blinkInPeriod(long unsigned int, long unsigned int, long unsigned int, long unsigned int)' here
   97 |   void blinkInPeriod(unsigned long onTime, unsigned long offTime, unsigned long blinkTime, unsigned long delayTime = 0);
      |        ^~~~~~~~~~~~~
/home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:179:6: error: default argument given for parameter 4 of 'void ezLED::blinkNumberOfTimes(long unsigned int, long unsigned int, unsigned int, long unsigned int)' [-fpermissive]
  179 | void ezLED::blinkNumberOfTimes(unsigned long onTime, unsigned long offTime, unsigned int numberOfTimes, unsigned long delayTime = 0) {
      |      ^~~~~
In file included from /home/fonso/Arduino/libraries/ezLED/src/ezLED.cpp:32:
/home/fonso/Arduino/libraries/ezLED/src/ezLED.h:98:8: note: previous specification in 'void ezLED::blinkNumberOfTimes(long unsigned int, long unsigned int, unsigned int, long unsigned int)' here
   98 |   void blinkNumberOfTimes(unsigned long onTime, unsigned long offTime, unsigned int numberOfTimes, unsigned long delayTime = 0);
      |        ^~~~~~~~~~~~~~~~~~
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

I appreciate if someone can help on this.

**Comment by ArduinoGetStarted** [comment]
Dear @hipotenusa,

Did you run the example code from the library ?

**Comment by hipotenusa** [comment]
Hi @ArduinoGetStarted,

Yes, I have tried different examples included within the library (LEDOnOff, LEDBlink, MultipleLED,..) and I am always getting the same compile errors. I have also tried today on a different machine and same thing.

You should be able to reproduce the error just selecting "LOLIN(WEMOS) D1 R2 & mini" as board in the Arduino IDE. This is not the only board I am getting error though (same happens for example with "Generic ESP8266 Module" or "ESP32 Dev module"). It compiles successfully with Arduino board "Arduino Mega or Mega 2560" for example.

Thanks for your help.

**Comment by hipotenusa** [comment]
Hi again,

After some reading and test, the problem seems to be due to redefining the default parameter in several functions of the class. I have removed the default values for parameters in .cpp -the remain in header- and now it compiles well.

[(https://stackoverflow.com/questions/6210450/the-compiler-is-complaining-about-my-default-parameters)](url)

**Comment by ArduinoGetStarted** [comment]
@hipotenusa 
It is great to hear that it is solved.

**Comment by hipotenusa** [comment]
HI, @ArduinoGetStarted,

It would be nice if you fix your .cpp removing the default values for arguments (which are already defined within the header) so whoever downloads your library will not face same compilation errors. I don´t know how to make a pull request, sorry.

Thanks for your time.

**Comment by ArduinoGetStarted** [comment]
@hipotenusa Thank you for your suggestion,
This problem does not happen in every case. The current library version works well with Arduino. So, this problem is not urgent. I will update it in the next release.

**Comment by mrNo0b** [comment]
I ran into the same issue... wanted to use this library, instead got like 30 compile errors...
and thanks to Hipotenusa solution I was able to make it compile by removing default values from .cpp functions
then I got error that analogWrite does not exists so I had to install `github.com/erropix/ESP32_AnalogWrite` library to fix it.
I use ESP32 Devkit v1 if that matters...

**Comment by ArduinoGetStarted** [comment]
@mrNo0b Thank you for reporting the issue. We will add a note about ESP32 Devkit v1 to the instruction.
By the way, I like your profile picture ^^
